### ISSUE TITLE
"Add" is not equivalent to "Set'

### ISSUE THREAD

**Issue by Gr3atsaga** [Kartones/vampire-survivors-savegame-editor#1]
The tool works, but where you say in the script file that the new coins amount will be "added" this is not true. It actually SETS the coins value instead of adding to it.

**Comment by Kartones** [comment]
You're right, it adds to the lifetime coins amount but sets the main coins amount, [so improved the description](https://github.com/Kartones/vampire-survivors-savegame-editor/commit/e26ee156fa5ab56390a4a40eb9241f4336f47b68) :+1: 

Thanks!
