### ISSUE TITLE
not able to find the js file?

### ISSUE THREAD

**Issue by soulceller** [Kartones/vampire-survivors-savegame-editor#4]
![2](https://user-images.githubusercontent.com/103814705/208224795-ce10fa64-50ef-4183-a030-f5894bbd73ce.PNG)
![3](https://user-images.githubusercontent.com/103814705/208224797-f45f326c-2b82-42aa-87d8-09d4da988779.PNG)
![4](https://user-images.githubusercontent.com/103814705/208224798-08df9dd1-fa2d-4093-9ef6-689f91d90154.PNG)
![cmd](https://user-images.githubusercontent.com/103814705/208224800-a9b2c697-7768-4055-a272-6b0cc34f3d9d.PNG)
:(

**Comment by Kartones** [comment]
oh, I think I recall reading something about having changed savegames on a recent patch. I'll take a look and either adapt the script or provide instructions accordingly, thanks for reporting!

**Comment by Kartones** [comment]
Hi again @soulceller . https://github.com/Kartones/vampire-survivors-savegame-editor/pull/5 should have fixed it, so get the latest version and give it a try!
